SourceCode/Web/RINOR_POS/ViewModels/employeeViewModel.cs
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using RINOR_POS;
using System.Web.Mvc;

namespace RINOR_POS.Models
{
    public class employeeViewModel
    {
        public employeeViewModel()
        {
            merchant_list = new List<pos_merchant_data>();
            brand_list = new List<pos_brand_data>();
            shop_list = new List<pos_shop_data>();
        }

        [Key]
        [Display(Name = "Employee")]
        public int employee_id { get; set; }

        [StringLength(20)]
        [Display(Name = "Employee NIK")]
        public string employee_nik { get; set; }

        [Display(Name = "Merchant")]
        public int MerchantId { get; set; }
        public string MerchantName { get; set; }
        [Display(Name = "Brand")]
        public int BrandId { get; set; }
        [Display(Name = "Brand Name")]
        public string BrandName { get; set; }
        [Required]
        [Display(Name = "Shop")]
        public int ShopID { get; set; }
        [Display(Name = "Shop Name")]
        public string ShopName { get; set; }
        public List<pos_merchant_data> merchant_list { get; set; }
        public List<pos_brand_data> brand_list { get; set; }
        public List<pos_shop_data> shop_list { get; set; }

        [StringLength(50)]
        [Display(Name = "Employee Name")]
        public string employee_name { get; set; }

        [StringLength(50)]
        [Display(Name = "Employee Email")]
        public string employee_email { get; set; }

        [Display(Name = "Activate")]
        public bool? fl_active { get; set; }
    }
}

SourceCode/Web/RINOR_POS/Controllers/employeeController.cs
using System;
using System.IO;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RINOR_POS.Models;

namespace RINOR_POS.Controllers
{
    [Authorize]
    public class employeeController : BaseController
    {
        private ModelPOSDB db = new ModelPOSDB();
        // GET: Employee
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// list for index
        /// </summary>
        /// <returns>JSON</returns>
        public JsonResult GetIndexList()
        {
            db.Configuration.ProxyCreationEnabled = false;

            var _qry = db.vw_employee.ToList();

            return Json(new { data = _qry }, JsonRequestBehavior.AllowGet);
        }

        // GET: roleUser/Create
        public ActionResult Create()
        {
            employeeViewModel Employee = new employeeViewModel()
            {
                merchant_list = db.pos_merchant_data.Where(o => o.DeletedDate == null).ToList(),
                brand_list = new List<pos_brand_data>(),
                shop_list = new List<pos_shop_data>(),
            };

            return View(Employee);
        }

        // POST: roleUser/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "employee_nik, ShopID, employee_name, employee_email, fl_active")] employeeViewModel employeedata)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    pos_employee pos_employee = new pos_employee();
                    pos_employee.employee_nik = employeedata.employee_nik;
                    pos_employee.ShopId = employeedata.ShopID;
                    pos_employee.employee_name = employeedata.employee_name;
                    pos_employee.employee_email = employeedata.employee_email;
                    pos_employee.fl_active = employeedata.fl_active;
                    pos_employee.created_by = UserProfile.employee_id;
                    pos_employee.created_date = DateTime.Now;
                    pos_employee = db.pos_employee.Add(pos_employee);
                    db.SaveChanges();

                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                string msgErr = string.Format("An unknown error has occurred , Please contact your system administrator. {0}", ex.Message);
                if (ex.InnerException != null)
                    msgErr += string.Format(" Inner Exception: {0}", ex.InnerException.Message);
                ModelState.AddModelError("", msgErr);
            }

            return View(employeedata);
        }

        // GET: roleUser/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            vw_employee emp_data = (from a in db.vw_employee.Where(a => a.employee_id == id)
                                    select a).FirstOrDefault<vw_employee>();
            if (emp_data == null)
            {
                return HttpNotFound("Crud not found.");
            }

            employeeViewModel employeeView = new employeeViewModel()
            {
                merchant_list = db.pos_merchant_data.Where(o => o.DeletedDate == null).ToList(),
                brand_list = db.pos_brand_data.Where(o => o.DeletedDate == null).ToList(),
                shop_list = db.pos_shop_data.Where(o => o.DeletedDate == null).ToList(),
                employee_id = emp_data.employee_id,
                employee_nik = emp_data.employee_nik,
                employee_name = emp_data.employee_name,
                employee_email = emp_data.employee_email,
                MerchantId = emp_data.MerchantID,
                BrandId = emp_data.BrandID,
                ShopID = Convert.ToInt32(emp_data.ShopId),
                fl_active = emp_data.fl_active
            };

            return View(employeeView);
        }

        // POST: crud/Edit
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "employee_id, employee_nik, ShopID, employee_name, employee_email, fl_active")] employeeViewModel employeedata)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    pos_employee pos_employee = db.pos_employee.Find(employeedata.employee_id);
                    pos_employee.employee_nik = employeedata.employee_nik;
                    pos_employee.ShopId = employeedata.ShopID;
                    pos_employee.employee_name = employeedata.employee_name;
                    pos_employee.employee_email = employeedata.employee_email;
                    pos_employee.fl_active = employeedata.fl_active;
                    pos_employee.updated_by = UserProfile.employee_id;
                    pos_employee.updated_date = DateTime.Now;
                    db.Entry(pos_employee).State = EntityState.Modified;
                    db.SaveChanges();

                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                string msgErr = string.Format("An unknown error has occurred , Please contact your system administrator. {0}", ex.Message);
                if (ex.InnerException != null)
                    msgErr += string.Format(" Inner Exception: {0}", ex.InnerException.Message);
                ModelState.AddModelError("", msgErr);
            }

            return View(employeedata);
        }

        // GET: roleUser/Setting/5
        public ActionResult Setting(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var checkUser = db.pos_user_application.Where(a => a.employee_id == id).ToList();

            user_accountViewModel user_app = new user_accountViewModel();
            if (checkUser.Count > 0)
                user_app = (from a in db.pos_employee.Where(a => a.employee_id == id)
                            join usr in db.pos_user_application on a.employee_id equals usr.employee_id into usrleft
                            from b in usrleft.DefaultIfEmpty()

                            select new user_accountViewModel
                            {
                                employee_id = a.employee_id,
                                employee_name = a.employee_name,
                                employee_nik = a.employee_nik,
                                user_id = b.user_id,
                                user_name = b.user_name,
                                user_password = b.user_password,
                                fl_active = b.fl_active,
                                UserRoleId = b.UserRoleId
                            }).FirstOrDefault<user_accountViewModel>();
            else
                user_app = (from a in db.pos_employee.Where(a => a.employee_id == id)
                            select new user_accountViewModel
                            {
                                employee_id = a.employee_id,
                                employee_name = a.employee_name,
                                employee_nik = a.employee_nik,
                                user_id = 0,
                                user_name = "",
                                fl_active = false,
                                UserRoleId = 0
                            }).FirstOrDefault<user_accountViewModel>();
            if (user_app == null)
            {
                return HttpNotFound("Crud not found.");
            }

            user_accountViewModel userView = new user_accountViewModel()
            {
                employee_id = user_app.employee_id,
                employee_name = user_app.employee_name,
                employee_nik = user_app.employee_nik,
                user_id = user_app.user_id,
                user_name = user_app.user_name,
                user_password = "",
                fl_active = user_app.fl_active,
                UserRoleId = user_app.UserRoleId,
                userrole_list = (from a in db.pos_user_role.Where(a => a.DeletedDate == null)
                                 select a).ToList<pos_user_role>()
            };

            return View(userView);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Setting([Bind(Include = "employee_id, user_id, user_name, user_password, fl_active, UserRoleId")] user_accountViewModel UserAccountData)
        {
            try
            {
                var checkUserName = db.pos_user_application.Where(a => a.user_name == UserAccountData.user_name && a.employee_id != UserAccountData.employee_id).ToList();
                if (checkUserName.Count > 0)
                    ModelState.AddModelError("user_name", "User Name Already Exist.");

                if (ModelState.IsValid)
                {
                    var checkexist = db.pos_user_application.Where(a => a.user_name == UserAccountData.user_name && a.employee_id == UserAccountData.employee_id).ToList();
                    if (checkexist.Count > 0)
                    {
                        //update
                        pos_user_application user_app = db.pos_user_application.Find(UserAccountData.user_id);

SourceCode/Web/RINOR_POS/Views/employee/Create.cshtml
@model RINOR_POS.Models.employeeViewModel

@{
    ViewBag.Title = "Employee";
}

<div id="content">
    <div class="row">
        <div class="col-xs-12 col-sm-9 col-md-9 col-lg-9">
            <h1 class="page-title txt-color-blueDark">

                <!-- PAGE HEADER -->
                <i class="fa-fw fa fa-pencil-square-o"></i>
                Employee
                <span>
                    >
                    New Data
                </span>
            </h1>
        </div>
    </div>

    <section id="widget-grid" class="">
        <div class="row">
            <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="jarviswidget" id="wid-id-3" data-widget-editbutton="false" data-widget-custombutton="false" data-widget-togglebutton="false" data-widget-collapsed="false">
                    <header>
                        <span class="widget-icon"> <i class="fa fa-edit"></i> </span>
                        <h2>Employee </h2>
                    </header>
                    <!-- widget div-->
                    <div>

                        <!-- widget edit box -->
                        <div class="jarviswidget-editbox">
                            <!-- This area used as dropdown edit box -->

                        </div>
                        <!-- end widget edit box -->
                        <!-- widget content -->
                        <div class="widget-body no-padding">

                            @using (Html.BeginForm("Create", "employee", FormMethod.Post, htmlAttributes: new { @class = "smart-form", enctype = "multipart/form-data" }))
                            {
                                <header>
                                    New Data Form
                                </header>

                                <fieldset>
                                    <fieldset>
                                        @Html.AntiForgeryToken()
                                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                        <br />
                                        @Html.HiddenFor(model => model.employee_id)
                                        <section>
                                            <div class="row">
                                                <div class="col-md-1">
                                                </div>
                                                <div class="col-md-2">
                                                    @Html.LabelFor(model => model.MerchantId, htmlAttributes: new { @class = "control-label" })
                                                </div>
                                                <div class="col-lg-2">
                                                    <label class="input">
                                                        @Html.DropDownListFor(model => model.MerchantId, new SelectList(Model.merchant_list, "MerchantID", "MerchantName"), "- Select Merchant -", htmlAttributes: new { id = "ddlMerchant", @class = "form-control select2", @onChange = "GetBrandList(this.value)" })
                                                    </label>
                                                </div>
                                            </div>
                                        </section>
                                        <section>
                                            <div class="row">
                                                <div class="col-md-1">
                                                </div>
                                                <div class="col-md-2">
                                                    @Html.LabelFor(model => model.BrandId, htmlAttributes: new { @class = "control-label" })
                                                </div>
                                                <div class="col-lg-2">
                                                    <label class="input">
                                                        @Html.DropDownListFor(model => model.BrandId, new SelectList(Model.brand_list, "BrandID", "BrandName"), "- Select Brand -", htmlAttributes: new { id = "ddlBrand", @class = "form-control select2", @onChange = "GetShopList(this.value)" })
                                                        @Html.ValidationMessageFor(model => model.BrandId, "", new { @class = "text-danger" })
                                                    </label>
                                                </div>
                                            </div>
                                        </section>
                                        <section>
                                            <div class="row">
                                                <div class="col-md-1">
                                                </div>
                                                <div class="col-md-2">
                                                    @Html.LabelRequiredFor(model => model.ShopID, htmlAttributes: new { @class = "control-label" })
                                                </div>
                                                <div class="col-lg-2">
                                                    <label class="input">
                                                        @Html.DropDownListFor(model => model.ShopID, new SelectList(Model.shop_list, "ShopId", "ShopName"), "- Select Shop -", htmlAttributes: new { id = "ddlShop", @class = "form-control select2" })
                                                        @Html.ValidationMessageFor(model => model.ShopID, "", new { @class = "text-danger" })
                                                    </label>
                                                </div>
                                            </div>
                                        </section>
                                        <section>
                                            <div class="row">
                                                <div class="col-md-1">
                                                </div>
                                                <div class="col-md-2">
                                                    @Html.LabelRequiredFor(model => model.employee_nik, htmlAttributes: new { @class = "control-label" })
                                                </div>
                                                <div class="col-lg-8">
                                                    <label class="input">
                                                        @Html.EditorFor(model => model.employee_nik, new { htmlAttributes = new { @class = "form-control col-lg-6", placeholder = "Employee NIK" } })
                                                        @Html.ValidationMessageFor(model => model.employee_nik, "", new { @class = "text-danger" })
                                                    </label>
                                                </div>
                                            </div>
                                        </section>
                                        <section>
                                            <div class="row">
                                                <div class="col-md-1">
                                                </div>
                                                <div class="col-md-2">
                                                    @Html.LabelRequiredFor(model => model.employee_name, htmlAttributes: new { @class = "control-label" })
                                                </div>
                                                <div class="col-lg-8">
                                                    <label class="input">
                                                        @Html.EditorFor(model => model.employee_name, new { htmlAttributes = new { @class = "form-control col-lg-6", placeholder = "Employee Name" } })
                                                        @Html.ValidationMessageFor(model => model.employee_name, "", new { @class = "text-danger" })
                                                    </label>
                                                </div>
                                            </div>
                                        </section>
                                        <section>
                                            <div class="row">
                                                <div class="col-md-1">
                                                </div>
                                                <div class="col-md-2">
                                                    @Html.LabelRequiredFor(model => model.employee_email, htmlAttributes: new { @class = "control-label" })
                                                </div>
                                                <div class="col-lg-8">
                                                    <label class="input">
                                                        @Html.EditorFor(model => model.employee_email, new { htmlAttributes = new { @class = "form-control col-lg-6", placeholder = "Employee Email" } })
                                                        @Html.ValidationMessageFor(model => model.employee_email, "", new { @class = "text-danger" })
                                                    </label>
                                                </div>
                                            </div>
                                        </section>
                                        <section>
                                            <div class="row">
                                                <div class="col-md-1">
                                                </div>
                                                <div class="col-md-2">
                                                    @Html.LabelFor(model => model.fl_active, htmlAttributes: new { @class = "control-label" })
                                                </div>
                                                <div class="col-lg-8">
                                                    <span class="onoffswitch-title"></span> <span class="onoffswitch">
                                                        <input type="checkbox" name="fl_active" id="chk_fl_active" class="onoffswitch-checkbox" value="true" @(Model.fl_active.GetValueOrDefault() ? "checked=\"checked\"" : "") />
                                                        <label class="onoffswitch-label" for="chk_fl_active">
                                                            <span class="onoffswitch-inner" data-swchon-text="Yes" data-swchoff-text="No"></span>
                                                            <span class="onoffswitch-switch"></span>
                                                        </label>
                                                    </span>
                                                </div>
                                            </div>
                                        </section>
                                    </fieldset>
                                </fieldset>

                                <footer>
                                    <div class="form-group">
                                        <div class="col-md-7">
                                            @Html.ActionLink("Cancel", "Index", "employee", htmlAttributes: new { @class = "btn btn-default" })
                                            <input type="submit" value="Save" class="btn btn-primary" />
                                        </div>
                                    </div>
                                </footer>

                            }
                        </div>
                    </div>
                </div>
            </article>
        </div>
    </section>
</div>

@section pagespecific {
    <script type="text/javascript">

        function GetBrandList(MerchantID) {
            var loc_id = $("#ddlMerchant").val();
            $.ajax({
                "url": baseURL + "productprice/GetBrandList?MerchantID=" + MerchantID,
                "type": "GET",
                "dataType": "json",
                success: function (data) {
                    var output = '<option value="0"> Select Brand </option>';
                    $.each(data, function (key, entry) {
                        output += '<option value=' + entry.BrandID + '>' + entry.BrandName + '</option>';
                    })
                    $("#ddlBrand").html(output);
                },
                error: function (err) {
                    alert(err);
                }
            });
        }

        function GetShopList(BrandID) {
            var loc_id = $("#ddlBrand").val();
            $.ajax({
                "url": baseURL + "productprice/GetShopList?BrandID=" + BrandID,
                "type": "GET",
                "dataType": "json",
                success: function (data) {
                    var output = '<option value="0"> Select Shop </option>';
                    $.each(data, function (key, entry) {
                        output += '<option value=' + entry.ShopID + '>' + entry.ShopName + '</option>';
                    })
                    $("#ddlShop").html(output);
                },
                error: function (err) {
                    alert(err);
                }
            });
        }
    </script>
}