SourceCode/License/RINOR_POS_LICENSE/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RINOR_POS.ModelLicence;

namespace RINOR_POS.Controllers
{
    public class homeController : Controller
    {
        private ModelLicencePOSDB db = new ModelLicencePOSDB();

        [Authorize]
        public ActionResult Index()
        {

            return View();
        }

        /// <summary>
        /// list for index
        /// </summary>
        /// <returns>JSON</returns>
        public JsonResult GetIndexList()
        {
            db.Configuration.ProxyCreationEnabled = false;

            var _qry = db.vw_pendingkey.Where(a => a.CountData > 0).ToList();

            return Json(new { data = _qry }, JsonRequestBehavior.AllowGet);
        }

        [AllowAnonymous]
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        [AllowAnonymous]
        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        
    }
}

SourceCode/License/RINOR_POS_LICENSE/Views/Shared/NotFound.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Not Found</title>
</head>
<body>
    <div style="background-color: grey; color: White; height: 10px;">
    </div>
    <div style="background-color: white; color: black; height: 170px;">
        <div style="padding:20px;">
            <h3>
                Application Error:
            </h3>
            <h4>
                Sorry, The Page, You are Looking for is not found.
            </h4>
            <h6>@Html.ActionLink("Go Back To Home Page", "Index", "Home")</h6>
            <br />
            <br />
        </div>
    </div>
    <div style="background-color: grey; color: White; height: 20px;">
    </div>
</body>
</html>

SourceCode/License/RINOR_POS_LICENSE/Views/Shared/_Aside.cshtml
<!-- Left panel : Navigation area -->
<!-- Note: This width of the aside area can be adjusted through LESS variables -->
<aside id="left-panel">

    <!-- User info -->
    @{ Html.RenderPartial("_CurrentUser"); }
    <!-- end user info -->
    <!-- NAVIGATION : This navigation is also responsive

    To make this navigation dynamic please make sure to link the node
    (the reference to the nav > ul) after page load. Or the navigation
    will not initialize.
    -->
    @{
        String currentUrl = Request.Url.ToString();
        string set_active = "";
        string set_style = "";

    }
    @model IEnumerable<RINOR_POS.ModelLicence.MenuViewModel>

    @if (Model != null && Request.IsAuthenticated)
    {
        var bases = Request.Url.GetLeftPart(UriPartial.Authority);
        var path = Request.ApplicationPath;
        var baseURL = bases + path + "/";
        <nav>
            <ul>
                @foreach (var Module in Model.Select(n => new { n.module_id, n.module_name }).Distinct())
                {
                    <li class="@Html.RouteIf(Module.module_name.ToLower(), "active")">
                        <a href="#">
                            @if (Module.module_name == "Home")
                            {
                                <i class="fa fa-lg fa-fw fa-home"></i>
                            }
                            else if (Module.module_name == "Manage Master")
                            {
                                <i class="fa fa-lg fa-fw fa-list-alt"></i>
                            }
                            else if (Module.module_name == "Manage User")
                            {
                                <i class="fa fa-lg fa-fw fa-group"></i>
                            }
                            else if (Module.module_name == "Administration")
                            {
                                <i class="fa fa-lg fa-fw fa-database"></i>
                            }
                            else if (Module.module_name == "Promotions")
                            {
                                <i class="fa fa-lg fa-fw fa-gift"></i>
                            }
                            else
                            {
                                <i class="fa fa-lg fa-fw fa-table"></i>
                            }

                            <span class="menu-item-parent">
                                @Module.module_name
                            </span>
                        </a>
                        @if (Request.Url.Segments.Length > 1)
                        {
                            String controllerUrl = Request.Url.Segments[1].ToString().ToLower();
                            foreach (RINOR_POS.ModelLicence.MenuViewModel mn in Model.Where(n => n.module_id == Module.module_id))
                            {
                                String controller_main = controllerUrl.Replace(@"/", "");
                                set_style = (mn.menu_url.ToLower().Equals(controller_main)) ? "display:block;" : "";
                            }
                        }

                        <ul style="@set_style">
                            @foreach (RINOR_POS.ModelLicence.MenuViewModel mn in Model.Where(n => n.module_id == Module.module_id))
                            {
                                if ((Request.Url.Segments.Length > 1) && (Request.Url.Segments.Length < 3))
                                {
                                    String controller_url = Request.Url.Segments[1].ToString().ToLower();
                                    String controller_1 = controller_url.Replace(@"/", "");
                                    set_active = (mn.menu_url.ToLower().Equals(controller_1)) ? "active" : "";

                                }
                                else if (Request.Url.Segments.Length == 3)
                                {
                                    String controller_url = Request.Url.Segments[1].ToString().ToLower();
                                    String controller_url_2 = Request.Url.Segments[2].ToString().ToLower();
                                    String controller_final = controller_url + controller_url_2;
                                    set_active = (mn.menu_url.ToLower().Equals(controller_final)) ? "active" : "";
                                }
                                else if (Request.Url.Segments.Length > 3)
                                {
                                    String controller_url = Request.Url.Segments[1].ToString().ToLower();
                                    String controller_1 = controller_url.Replace(@"/", "");
                                    set_active = (mn.menu_url.ToLower().Equals(controller_1)) ? "active" : "";
                                }
                                else
                                {
                                    if (Request.Url.Segments[0] == @"/")
                                    {
                                        String controller_url = Request.Url.Segments[0].ToString().ToLower();
                                        set_active = (mn.menu_url.ToLower().Equals("")) ? "active" : "";
                                        //set_active = "active";
                                    }
                                    else
                                    {
                                        String controller_url = Request.Url.Segments[1].ToString().ToLower();
                                        set_active = (mn.menu_url.ToLower().Equals(controller_url)) ? "active" : "";
                                    }

                                }

                                <li class="@set_active">
                                    <a href="@Url.Action("index", mn.menu_url, null, Request.Url.Scheme, Request.Url.Host)">
                                        @if (mn.menu_name == "Dashboard")
                                        {
                                            <i class="fa fa-lg fa-fw fa-bar-chart-o"></i>
                                        }
                                        else if (mn.menu_name == "Preferences")
                                        {
                                            <i class="fa fa-lg fa-fw fa-cogs"></i>
                                        }
                                        else if (mn.menu_name.Contains("Product VAT"))
                                        {
                                            <i class="fa fa-lg fa-fw fa-suitcase"></i>
                                        }
                                        else if (mn.menu_name == "Sale Mode")
                                        {
                                            <i class="fa fa-lg fa-fw fa-list-ol"></i>
                                        }
                                        else if (mn.menu_name.Contains("Credit Card"))
                                        {
                                            <i class="fa fa-lg fa-fw fa-credit-card"></i>
                                        }
                                        else if (mn.menu_name == "Payment Type")
                                        {
                                            <i class="fa fa-lg fa-fw fa-money"></i>
                                        }
                                        else if (mn.menu_name.Contains("Computer"))
                                        {
                                            <i class="fa fa-lg fa-fw fa-desktop"></i>
                                        }
                                        else if (mn.menu_name == "Manage Printer")
                                        {
                                            <i class="fa fa-lg fa-fw fa-print"></i>
                                        }
                                        else if (mn.menu_name == "Manage Bill")
                                        {
                                            <i class="fa fa-lg fa-fw fa-book"></i>
                                        }
                                        else if (mn.menu_name == "Manage Receipt")
                                        {
                                            <i class="fa fa-lg fa-fw fa-book"></i>
                                        }
                                        else if (mn.menu_name == "Manage Reason")
                                        {
                                            <i class="fa fa-lg fa-fw fa-comments-o"></i>
                                        }
                                        else if (mn.menu_name == "Manage Module")
                                        {
                                            <i class="fa fa-lg fa-fw fa-th-large"></i>
                                        }
                                        else if (mn.menu_name == "Manage Menu")
                                        {
                                            <i class="fa fa-lg fa-fw fa-th"></i>
                                        }
                                        else if (mn.menu_name == "Manage Role")
                                        {
                                            <i class="fa fa-lg fa-fw fa-lock"></i>
                                        }
                                        else if (mn.menu_name == "Register User")
                                        {
                                            <i class="fa fa-lg fa-fw fa-user"></i>
                                        }
                                        else if (mn.menu_name == "Manage Promo")
                                        {
                                            <i class="fa fa-lg fa-fw fa-gift"></i>
                                        }
                                        else if (mn.menu_name == "Merchant Data")
                                        {
                                            <i class="fa fa-lg fa-fw fa-building "></i>
                                        }
                                        else if (mn.menu_name == "Brand Data")
                                        {
                                            <i class="fa fa-lg fa-fw fa-flag-o"></i>
                                        }
                                        else if (mn.menu_name == "Shop Data")
                                        {
                                            <i class="fa fa-lg fa-fw fa-institution"></i>
                                        }
                                        else if (mn.menu_name == "Product Data")
                                        {
                                            <i class="fa fa-lg fa-fw fa-cutlery"></i>
                                        }
                                        else if (mn.menu_name == "Product Price")
                                        {
                                            <i class="fa fa-lg fa-fw fa-tags"></i>
                                        }
                                        else
                                        {
                                            <i class="fa fa-lg fa-fw fa-inbox"></i>}
                                        <span class="menu-item-parent">@mn.menu_name</span>
                                    </a>
                                </li>
                            }

                        </ul>
                    </li>
                }
            </ul>
        </nav>

    }

    <span class="minifyme" data-action="minifyMenu">
        <i class="fa fa-arrow-circle-left hit"></i>
    </span>

</aside>
<!-- END NAVIGATION -->

SourceCode/License/RINOR_POS_LICENSE/Views/Shared/_CurrentUser.cshtml
<div class="login-info">
    <span id="activity" class="activity-dropdown">
        <!-- <a href="javascript:void(0);" id="activity" class="activity-dropdown"> -->
        <a href="#" id="activity" class="activity-dropdown">
            <img src="~/content/img/avatars/sunny.png" alt="me" class="online" />
            <span>@RINOR_POS.ModelLicence.UserProfile.UserName</span>
            <i class="fa fa-angle-down"></i>
        </a>
    </span>
    <!-- AJAX-DROPDOWN : control this dropdown height, look and feel from the LESS variable file -->
    <div class="ajax-dropdown">

        <!-- the ID links are fetched via AJAX to the ajax container "ajax-notifications" -->

        <div class="btn-group btn-group-justified">
            <label class="btn btn-default">
                Your Login Information
            </label>
            <a href="@Url.Action("changepassword", "account")" class="btn btn-default btn-primary" target="_self">Change Password</a>
        </div>

        @*<div class="btn btn-group-sm"">
            <button class="btn btn-group-sm">
                <a href="@Url.Action("changepassword", "account")">Change Password</a>
            </button>
        </div>*@

        <!-- notification content -->
        <div class="ajax-notifications custom-scroll">
            <div class="alert alert-transparent table-responsive">
                @*<h4>Your Login Info</h4>*@
                @*<p>User ID : @RINOR_POS.ModelLicence.UserProfile.UserId; </p>
                    <p>User Name : @RINOR_POS.ModelLicence.UserProfile.UserName; </p>
                    <p>User Full Name : @RINOR_POS.ModelLicence.UserProfile.UserFullName; </p>
                    <p>Company Name : @RINOR_POS.ModelLicence.UserProfile.CompanyName; </p>
                    <p>Dept Name : @RINOR_POS.ModelLicence.UserProfile.DeptName; </p>
                    <p>Org ID : @RINOR_POS.ModelLicence.UserProfile.OrgId; </p>
                    <p>Employee ID : @RINOR_POS.ModelLicence.UserProfile.employee_id; </p>
                    <p>Employee Name : @RINOR_POS.ModelLicence.UserProfile.Employee; </p>*@
                <table class="table table-sm">
                    <tbody>
                        @if (RINOR_POS.ModelLicence.UserProfile.UserId > 0)
                        {
                            <tr>
                                <th scope="row">Login Id</th>
                                <td>@RINOR_POS.ModelLicence.UserProfile.UserId</td>
                            </tr>
                        }

                        @if (!string.IsNullOrWhiteSpace(RINOR_POS.ModelLicence.UserProfile.UserName))
                        {
                            <tr>
                                <th scope="row">Login Name</th>
                                <td>@RINOR_POS.ModelLicence.UserProfile.UserName</td>
                            </tr>
                        }

                        @if (@RINOR_POS.ModelLicence.UserProfile.pos_employee != null)
                        {
                            <tr>
                                <th scope="row">Employee NIK</th>
                                <td>
                                    @RINOR_POS.ModelLicence.UserProfile.pos_employee.employee_nik
                                </td>
                            </tr>

                            <tr>
                                <th scope="row">Employee Name</th>
                                <td>
                                    @RINOR_POS.ModelLicence.UserProfile.pos_employee.employee_name.ToUpper()
                                </td>
                            </tr>

                            <tr>
                                <th scope="row">Employee Email</th>
                                <td>
                                    @RINOR_POS.ModelLicence.UserProfile.pos_employee.employee_email
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>

            </div>
        </div>
        <!-- end notification content -->
        <!-- footer: refresh area -->
        <span>
            Last updated on: 12-07-2019 9:43AM
            <button type="button" data-loading-text="<i class='fa fa-refresh fa-spin'></i> Loading..." class="btn btn-xs btn-default pull-right">
                <i class="fa fa-refresh"></i>
            </button>
        </span>
        <!-- end footer -->

    </div>
    <!-- END AJAX-DROPDOWN -->
</div>

SourceCode/License/RINOR_POS_LICENSE/Views/Shared/_Footer.cshtml
    <!-- PAGE FOOTER -->
<div class="page-footer">
    <div class="row">
        <div class="col-xs-12 col-sm-6">
            <span class="txt-color-white"><span class="hidden-xs"></span>PT. Rinor Inter Solusindo © @DateTime.Now.Year  - All Rights Reserved </span>
        </div>
        <div class="col-xs-6 col-sm-6 text-right hidden-xs">
            <div class="txt-color-white inline-block">
                <i class="txt-color-white">Rinor Secure System Ver 1.0.0 </i>
            </div>
        </div>
                <!--
                <div class="col-xs-6 col-sm-6 text-right hidden-xs">
                    <div class="txt-color-white inline-block">
                        <i class="txt-color-blueLight hidden-mobile">Last account activity <i class="fa fa-clock-o"></i> <strong>52 mins ago &nbsp;</strong> </i>
                        <div class="btn-group dropup">
                            <button class="btn btn-xs dropdown-toggle bg-color-blue txt-color-white" data-toggle="dropdown">
                                <i class="fa fa-link"></i> <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu pull-right text-left">
                                <li>
                                    <div class="padding-5">
                                        <p class="txt-color-darken font-sm no-margin">Download Progress</p>
                                        <div class="progress progress-micro no-margin">
                                            <div class="progress-bar progress-bar-success" style="width: 50%;"></div>
                                        </div>
                                    </div>
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <div class="padding-5">
                                        <p class="txt-color-darken font-sm no-margin">Server Load</p>
                                        <div class="progress progress-micro no-margin">
                                            <div class="progress-bar progress-bar-success" style="width: 20%;"></div>
                                        </div>
                                    </div>
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <div class="padding-5">
                                        <p class="txt-color-darken font-sm no-margin">Memory Load <span class="text-danger">*critical*</span></p>
                                        <div class="progress progress-micro no-margin">
                                            <div class="progress-bar progress-bar-danger" style="width: 70%;"></div>
                                        </div>
                                    </div>
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <div class="padding-5">
                                        <button class="btn btn-block btn-default">refresh</button>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                    -->
            </div>
        </div>
        <!-- END PAGE FOOTER -->

SourceCode/License/RINOR_POS_LICENSE/Views/Shared/_Header.cshtml
    <!-- HEADER -->
<header id="header">
    <div id="logo-group">
@if (Request.IsAuthenticated)
{
        <!-- PLACE YOUR LOGO HERE -->
        <span id="logo"><label class="panel-title">Rinor Secure System</label></span>
        <!-- END LOGO PLACEHOLDER -->
    <div class="row">
        @*<div id="MyDateDisplay" class="date" onload="showDate()"></div>
        <div id="MyClockDisplay" class="clock" onload="showTime()"></div>*@
    </div>
            <!-- Note: The activity badge color changes when clicked and resets the number to 0
            Suggestion: You may want to set a flag when this happens to tick off all checked messages / notifications -->
            <!-- <span id="activity" class="activity-dropdown"> <i class="fa fa-user"></i> <b class="badge"> 21 </b> </span> -->

        <!-- AJAX-DROPDOWN : control this dropdown height, look and feel from the LESS variable file -->
            <div class="ajax-dropdown">

                <!-- the ID links are fetched via AJAX to the ajax container "ajax-notifications" -->
                <div class="btn-group btn-group-justified" data-toggle="buttons">
                    <label class="btn btn-default">
                        <input type="radio" name="activity" id="~/content/ajax/notify/mail.html">
                        Msgs (14)
                    </label>
                    <label class="btn btn-default">
                        <input type="radio" name="activity" id="~/content/ajax/notify/notifications.html">
                        notify (3)
                    </label>
                    <label class="btn btn-default">
                        <input type="radio" name="activity" id="~/content/ajax/notify/tasks.html">
                        Tasks (4)
                    </label>
                </div>

                <!-- notification content -->
                <div class="ajax-notifications custom-scroll">

                    <div class="alert alert-transparent">
                        <h4>Click a button to show messages here</h4>
                        This blank page message helps protect your privacy, or you can show the first message here automatically.
                    </div>

                    <i class="fa fa-lock fa-4x fa-border"></i>

                </div>
                <!-- end notification content -->
                <!-- footer: refresh area -->
                <span>
                    Last updated on: 12/12/2013 9:43AM
                    <button type="button" data-loading-text="<i class='fa fa-refresh fa-spin'></i> Loading..." class="btn btn-xs btn-default pull-right">
                    <i class="fa fa-refresh"></i>
                </button>
                </span>
                <!-- end footer -->

            </div>
            <!-- END AJAX-DROPDOWN -->
        }
    </div>
    <section id="top-right">
        @if (@Model is HelperResult)
        {
            @Model
        }
        else
        {
            <div class="pull-right">
                @Html.Partial("_TopRight")
            </div>
        }
    </section>
</header>
<!-- END HEADER -->

SourceCode/License/RINOR_POS_LICENSE/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en-us" id="@ViewBag.PageId" class="@Settings.CurrentTheme">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>Rinor Secure System</title>
    <meta name="description" content="">
    <meta name="author" content="">

    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    @*<script> if (!window.jQuery) { document.write('<script src="./scripts/libs/jquery-2.1.1.min.js"><\/script>'); } </script>*@
    @*<script> if (!window.jQuery.ui) { document.write('<script src="./scripts/libs/jquery-ui-1.10.3.min.js"><\/script>'); } </script>*@

    <!-- Basic Styles -->
    @Styles.Render("~/content/smartadmin")
    <!-- FAVICONS -->
    <link rel="shortcut icon" href="~/content/img/favicon/favicon.ico" type="image/x-icon">
    <link rel="icon" href="~/content/img/favicon/favicon.ico" type="image/x-icon">

    <!-- GOOGLE FONT -->
    <link rel="stylesheet" href="~/content/css/OpenSans.css">
    <style type="text/css">
          .clock {
        position: absolute;
        top: 68%;
        left: 50%;
        transform: translateX(-50%) translateY(-50%);
        color: slategray;
        font-size: 12pt;
        font-weight: bold;
        font-family: Arial;
        /*letter-spacing: 7px; */
    }

    .date {
        position: absolute;
        top: 30%;
        left: 50%;
        transform: translateX(-50%) translateY(-50%);
        color: slategray;
        font-size: 12pt;
        font-weight: bold;
        font-family: Arial;
        /*letter-spacing: 7px; */
    }
    </style>
    <!-- Specifying a Webpage Icon for Web Clip
         Ref: https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html -->
    <link rel="apple-touch-icon" href="~/content/img/splash/sptouch-icon-iphone.png">
    <link rel="apple-touch-icon" sizes="76x76" href="~/content/img/splash/touch-icon-ipad.png">
    <link rel="apple-touch-icon" sizes="120x120" href="~/content/img/splash/touch-icon-iphone-retina.png">
    <link rel="apple-touch-icon" sizes="152x152" href="~/content/img/splash/touch-icon-ipad-retina.png">

    <!-- iOS web-app metas : hides Safari UI Components and Changes Status Bar Appearance -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">

    <!-- Startup image for web apps -->
    <link rel="apple-touch-startup-image" href="~/content/img/splash/ipad-landscape.png" media="screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:landscape)">
    <link rel="apple-touch-startup-image" href="~/content/img/splash/ipad-portrait.png" media="screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:portrait)">
    <link rel="apple-touch-startup-image" href="~/content/img/splash/iphone.png" media="screen and (max-device-width: 320px)">
</head>
<body class="@ViewBag.PageClass @Settings.CurrentTheme">
    @{ Html.RenderPartial("_Header", RenderSection("topright", false)); }
    @if (Request.IsAuthenticated)
    {
        @Html.Action("MenuNavigation", "menu_navigation")
    }

    @*@{ Html.RenderPartialIf("_Aside", Request.IsAuthenticated); }*@

        @*@{ Html.RenderPartial("_Aside"); }*@

        <div id="main" role="main">
            @{ Html.RenderPartialIf("_Ribbon", Request.IsAuthenticated); }
            @RenderBody()
        </div>

        @if (Request.IsAuthenticated)
        {
            Html.RenderPartial("_Footer");
            Html.RenderPartialIf("_Tiles", Settings.EnableTiles);
        }
        @{ Html.RenderPartial("_Scripts", RenderSection("pagespecific", false)); }

        @*@{ Html.RenderPartial("_Aside"); }
            <div id="main" role="main">
                @{ Html.RenderPartial("_Ribbon"); }
                @RenderBody()
            </div>
            @{ Html.RenderPartial("_Footer");
            @{ Html.RenderPartialIf("_Tiles", Settings.EnableTiles); }
            @{ Html.RenderPartial("_Scripts", RenderSection("pagespecific", false)); }*@
    </body>
</html>

<script type="text/javascript">
        
</script>

SourceCode/License/RINOR_POS_LICENSE/Views/Shared/_Tiles.cshtml
<!-- SHORTCUT AREA : With large tiles (activated via clicking user name tag)
Note: These tiles are completely responsive,
you can add as many as you like
-->
<div id="shortcut">
    <ul>
        <li>
            <a href="@Url.Action("inbox", "home")" class="jarvismetro-tile big-cubes bg-color-blue"> <span class="iconbox"> <i class="fa fa-envelope fa-4x"></i> <span>Mail <span class="label pull-right bg-color-darken">14</span></span> </span> </a>
        </li>
        <li>
            <a href="@Url.Action("calendar", "home")" class="jarvismetro-tile big-cubes bg-color-orangeDark"> <span class="iconbox"> <i class="fa fa-calendar fa-4x"></i> <span>Calendar</span> </span> </a>
        </li>
        <li>
            <a href="@Url.Action("googlemap", "home")" class="jarvismetro-tile big-cubes bg-color-purple"> <span class="iconbox"> <i class="fa fa-map-marker fa-4x"></i> <span>Maps</span> </span> </a>
        </li>
        <li>
            <a href="@Url.Action("invoice", "misc")" class="jarvismetro-tile big-cubes bg-color-blueDark"> <span class="iconbox"> <i class="fa fa-book fa-4x"></i> <span>Invoice <span class="label pull-right bg-color-darken">99</span></span> </span> </a>
        </li>
        <li>
            <a href="@Url.Action("gallery", "appviews")" class="jarvismetro-tile big-cubes bg-color-greenLight"> <span class="iconbox"> <i class="fa fa-picture-o fa-4x"></i> <span>Gallery </span> </span> </a>
        </li>
        <li>
            <a href="@Url.Action("profile", "appviews")" class="jarvismetro-tile big-cubes selected bg-color-pinkDark"> <span class="iconbox"> <i class="fa fa-user fa-4x"></i> <span>My Profile </span> </span> </a>
        </li>
    </ul>
</div>
<!-- END SHORTCUT AREA -->