SourceCode/Web/RINOR_POS/ViewModels/printerViewModel.cs
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using RINOR_POS;

namespace RINOR_POS.Models
{
    public class printertypeViewModel
    {
        [Key]
        public int PrinterTypeID { get; set; }

        [Required]
        [StringLength(150)]
        [Display(Name = "Printer Type")]
        public string PrinterTypeName { get; set; }
    }
    public class printerViewModel
    {
        public printerViewModel()
        {
            printer_type_list = new List<pos_printer_type>();
        }

        [Key]
        public int PrinterID { get; set; }

        [Required]
        [Display(Name = "Printer Type")]
        public int PrinterTypeID { get; set; }

        public string PrinterTypeName { get; set; }

        public List<pos_printer_type> printer_type_list { get; set; }

        [Required]
        [StringLength(100)]
        [Display(Name = "Printer Name")]
        public string PrinterName { get; set; }

        [StringLength(255)]
        [Display(Name = "Printer Device")]
        public string PrinterDeviceName { get; set; }

        [StringLength(255)]
        [Display(Name = "Printer Device Backup")]
        public string PrinterDeviceBackup { get; set; }

        [Display(Name = "Is Opos Printer")]
        public bool? IsOposPrinter { get; set; }

        [Display(Name = "Printer Status")]
        public int? PrinterStatus { get; set; }

        [StringLength(255)]
        [Display(Name = "Printer Name For Print")]
        public string PrinterNameForPrint { get; set; }

        [Display(Name = "Paper Width")]
        public int? PaperWidth { get; set; }

        [Display(Name = "Line Spacing")]
        public int? LineSpacing { get; set; }

        [Display(Name = "Margin Top")]
        public int? MarginTop { get; set; }

        [Display(Name = "Margin Left")]
        public int? MarginLeft { get; set; }

        [Display(Name = "Margin Right")]
        public int? MarginRight { get; set; }

        [Display(Name = "Margin Bottom")]
        public int? MarginBottom { get; set; }
    }
}

SourceCode/Web/RINOR_POS/Controllers/printerController.cs
using System;
using System.IO;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RINOR_POS.Models;

namespace RINOR_POS.Controllers
{
    [Authorize]
    public class printerController : BaseController
    {
        private ModelPOSDB db = new ModelPOSDB();

        // GET: print
        public ActionResult Index(int id = 0)
        {
            var printtype = db.pos_printer_type.Find(id);
            printerViewModel printerView = new printerViewModel()
            {
                PrinterTypeID = id,
                PrinterTypeName = printtype.PrinterTypeName
            };
            return View(printerView);
        }

        /// <summary>
        /// list for index
        /// </summary>
        /// <returns>JSON</returns>
        public JsonResult GetIndexList(int id = 0)
        {
            db.Configuration.ProxyCreationEnabled = false;

            var _qry = (from a in db.pos_printers.Where(a => a.DeletedDate == null && a.PrinterTypeID == id)
                        join b in db.pos_printer_type on a.PrinterTypeID equals b.PrinterTypeID

                        select new printerViewModel
                        {
                            PrinterID = a.PrinterID,
                            PrinterName = a.PrinterName,
                            PrinterTypeName = b.PrinterTypeName,
                            PrinterDeviceName = a.PrinterDeviceName,
                            PrinterNameForPrint = a.PrinterNameForPrint,
                            PaperWidth = a.PaperWidth,
                            LineSpacing = a.LineSpacing,
                            MarginTop = a.MarginTop,
                            MarginBottom = a.MarginBottom,
                            MarginLeft = a.MarginLeft,
                            MarginRight = a.MarginRight,
                        }).ToList<printerViewModel>();

            List<printerViewModel> Printers = new List<printerViewModel>();
            foreach (printerViewModel printerview in _qry)
            {
                printerViewModel printer = new printerViewModel();
                printer.PrinterID = printerview.PrinterID;
                printer.PrinterName = printerview.PrinterName;
                printer.PrinterDeviceName = printerview.PrinterDeviceName;
                printer.PrinterTypeName = printerview.PrinterTypeName;
                printer.PrinterNameForPrint = string.Format("[{0}] [Margin: {1} {2} {3} {4}] [Width: {5}] [Line-Spacing: {6}]",
                                                    printerview.PrinterNameForPrint,
                                                    printerview.MarginTop, printerview.MarginLeft, printerview.MarginRight, printerview.MarginBottom,
                                                    printerview.PaperWidth, printerview.LineSpacing);
                Printers.Add(printer);
            }
            return Json(new { data = Printers }, JsonRequestBehavior.AllowGet);
        }

        // GET: printer/Create
        public ActionResult Create(int id = 0)
        {
            printerViewModel printerView = new printerViewModel()
            {
                PrinterTypeID = id,
                PaperWidth = 0,
                LineSpacing = 0,
                MarginTop = 0,
                MarginBottom = 0,
                MarginLeft = 0,
                MarginRight = 0
            };
            return View(printerView);
        }

        // POST: crud/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(printerViewModel printer_data)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    pos_printers pos_printers = new pos_printers()
                    {
                        PrinterTypeID = printer_data.PrinterTypeID,
                        PrinterName = printer_data.PrinterName,
                        PrinterDeviceName = printer_data.PrinterDeviceName,
                        PrinterDeviceBackup = printer_data.PrinterDeviceBackup,
                        PrinterNameForPrint = printer_data.PrinterNameForPrint,
                        PaperWidth = printer_data.PaperWidth,
                        LineSpacing = printer_data.LineSpacing,
                        MarginTop = printer_data.MarginTop,
                        MarginLeft = printer_data.MarginLeft,
                        MarginRight = printer_data.MarginRight,
                        MarginBottom = printer_data.MarginBottom,
                        IsOposPrinter = printer_data.IsOposPrinter,
                        PrinterStatus = printer_data.PrinterStatus,
                        CreatedDate = DateTime.Now,
                        CreatedBy = UserProfile.UserId
                    };
                    pos_printers = db.pos_printers.Add(pos_printers);
                    db.SaveChanges();

                    return RedirectToAction("Index", new { id = printer_data.PrinterTypeID });
                }
            }
            catch (Exception ex)
            {
                string msgErr = string.Format("An unknown error has occurred , Please contact your system administrator. {0}", ex.Message);
                if (ex.InnerException != null)
                    msgErr += string.Format(" Inner Exception: {0}", ex.InnerException.Message);
                ModelState.AddModelError("", msgErr);
            }

            return View(printer_data);
        }

        // GET: crud/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            pos_printers printer_data = db.pos_printers.Find(id);
            if (printer_data == null)
            {
                return HttpNotFound("Product VAT not found.");
            }

            printerViewModel printer_model = new printerViewModel()
            {
                PrinterID = printer_data.PrinterID,
                PrinterTypeID = printer_data.PrinterTypeID,
                PrinterName = printer_data.PrinterName,
                PrinterDeviceName = printer_data.PrinterDeviceName,
                PrinterDeviceBackup = printer_data.PrinterDeviceBackup,
                PrinterNameForPrint = printer_data.PrinterNameForPrint,
                PaperWidth = printer_data.PaperWidth,
                LineSpacing = printer_data.LineSpacing,
                MarginTop = printer_data.MarginTop,
                MarginLeft = printer_data.MarginLeft,
                MarginRight = printer_data.MarginRight,
                MarginBottom = printer_data.MarginBottom,
                IsOposPrinter = printer_data.IsOposPrinter,
                PrinterStatus = printer_data.PrinterStatus,
            };

            return View(printer_model);
        }

        // POST: crud/Edit
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(printerViewModel printer_data)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    pos_printers pos_printers = db.pos_printers.Find(printer_data.PrinterID);
                    //pos_printers.PrinterTypeID = printer_data.PrinterTypeID;
                    pos_printers.PrinterName = printer_data.PrinterName;
                    pos_printers.PrinterDeviceName = printer_data.PrinterDeviceName;
                    pos_printers.PrinterDeviceBackup = printer_data.PrinterDeviceBackup;
                    pos_printers.PrinterNameForPrint = printer_data.PrinterNameForPrint;
                    pos_printers.PaperWidth = printer_data.PaperWidth;
                    pos_printers.LineSpacing = printer_data.LineSpacing;
                    pos_printers.MarginTop = printer_data.MarginTop;
                    pos_printers.MarginLeft = printer_data.MarginLeft;
                    pos_printers.MarginRight = printer_data.MarginRight;
                    pos_printers.MarginBottom = printer_data.MarginBottom;
                    pos_printers.IsOposPrinter = printer_data.IsOposPrinter;
                    pos_printers.PrinterStatus = printer_data.PrinterStatus;
                    pos_printers.UpdatedDate = DateTime.Now;
                    pos_printers.UpdatedBy = UserProfile.UserId;

                    db.Entry(pos_printers).State = EntityState.Modified;
                    db.SaveChanges();

                    return RedirectToAction("Index", new { id = printer_data.PrinterTypeID });
                }
            }
            catch (Exception ex)
            {
                string msgErr = string.Format("An unknown error has occurred , Please contact your system administrator. {0}", ex.Message);
                if (ex.InnerException != null)
                    msgErr += string.Format(" Inner Exception: {0}", ex.InnerException.Message);
                ModelState.AddModelError("", msgErr);
            }

            return View(printer_data);
        }

        // POST: crud/Delete/5
        [HttpGet]
        public JsonResult DeleteItem(int id)
        {
            pos_printers pos_printers = db.pos_printers.Find(id);
            if (pos_printers != null)
            {
                pos_printers.DeletedBy = UserProfile.UserId;
                pos_printers.DeletedDate = DateTime.Now;
                db.Entry(pos_printers).State = EntityState.Modified;
                db.SaveChanges();

                return Json(1, JsonRequestBehavior.AllowGet);
            }

SourceCode/Web/RINOR_POS/Views/printer/Index.cshtml
@model RINOR_POS.Models.printerViewModel

@{
    ViewBag.Title = "Printer";
}

<div id="content">
    <!-- row -->
    <div class="row">
        <div class="col-xs-12 col-sm-9 col-md-9 col-lg-9">
            <h1 class="page-title txt-color-blueDark">

                <!-- PAGE HEADER -->
                <i class="fa-fw fa fa-pencil-square-o"></i>
                Printer
                <span>
                    >
                    @Model.PrinterTypeName
                </span>
            </h1>
        </div>

        <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">
            <!-- Button trigger modal -->
            <a class="btn btn-primary btn-lg pull-right header-btn hidden-mobile" href="@Url.Action("Create", "printer", new { id = Model.PrinterTypeID }, Request.Url.Scheme)"><i class='fa fa-plus'></i> Printer</a>
            @Html.HiddenFor(model => model.PrinterTypeID, new { id = "hdnID" })
        </div>
    </div>
    <section>
        <div class="row">
            <div class="col-lg-12" style="margin-bottom:5px">
                <a class="btn btn-default btn-sm pull-right header-btn hidden-mobile" href="@Url.Action("index", "printtype", Request.Url.Scheme)"><i class='fa fa-arrow-left'></i> Back to Printer Type</a>
            </div>
        </div>
    </section>
    <section id="widget-grid" class="">
        <div class="row">
            <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="jarviswidget jarviswidget-color-darken" id="wid-id-0" data-widget-editbutton="false">

                    <header>
                        <span class="widget-icon"> <i class="fa fa-table"></i> </span>
                        <h2>Printer List</h2>

                    </header>
                    <div>
                        <!-- widget edit box -->
                        <div class="jarviswidget-editbox">
                            <!-- This area used as dropdown edit box -->

                        </div>
                        <!-- end widget edit box -->
                        <div class="widget-body no-padding">
                            <table class="table table-striped table-bordered table-hover" width="100%" id="table_basic">
                                <thead>
                                    <tr>
                                        <th>
                                            @Html.DisplayNameFor(model => model.PrinterName)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.PrinterDeviceName)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.PrinterTypeName)
                                        </th>
                                        <th width="30%">
                                            Printer Property
                                        </th>
                                        <th width="10px">Edit</th>
                                        <th width="10px">Delete</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </article>
        </div>
    </section>
    <!-- Modal -->
    <div class="modal fade" id="InfoAsset" tabindex="-1" role="dialog"></div>
</div>

@section pagespecific {
    <script type="text/javascript">

        function DeleteData(id) {
            swal({
                title: "Are you sure want to Delete this data?",
                text: "(this process can\'t be undo)",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Yes, Sure!",
                closeOnConfirm: false,
                closeOnEsc: false,
                closeOnCancel: false,
                showLoaderOnConfirm: true,
                preConfirm: () => {
                    return new Promise(() => {
                        //ajax side
                        swal({
                            title: 'Please wait... delete data in progress....',
                            onOpen: function () {
                                swal.showLoading()
                                $.ajax({
                                    type: "GET",
                                    url: baseURL + "printer/DeleteItem/" + id,
                                    success: function (data) {
                                        if (data == "1") {
                                            swal.close();
                                            swal("Success", "Success Delete Data", "success");
                                            setTimeout(location.reload(true), 5000);
                                            //window.location.href = "/asset_registration/index";
                                        }
                                        else {
                                            swal("Failed", "Failed Delete Data", "error");
                                        }

                                    },
                                });
                            }
                        });
                    })
                },
                allowOutsideClick: () => !swal.isLoading()
            }).then((result) => {
                if (result.dismiss) {
                    swal("Cancel", "You Cancel Delete Data", "error");
                }
            });
        }

        $(document).ready(function () {
            var id = document.getElementById("hdnID").value;
            $('#table_basic').dataTable(
                {
                    "ajax": {
                        "url": baseURL + "printer/GetIndexList?id=" + id,
                        "type": "GET",
                        "datatype": "json",
                    },
                    "dom": "<'dt-toolbar'<'col-xs-12 col-sm-6'f><'col-sm-6 col-xs-12 hidden-xs'l>r>" + "t"
                        + "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-xs-12 col-sm-6'p>>",
                    "columns": [
                        { "data": "PrinterName", "autoWidth": true },
                        { "data": "PrinterDeviceName", "autoWidth": true },
                        { "data": "PrinterTypeName", "autoWidth": true },
                        { "data": "PrinterNameForPrint", "autoWidth": true },
                        {
                            "data": "action",
                            "autowidth": true,
                            "mRender": function (data, type, full) {
                                return '<a href="' + baseURL + 'printer/edit/' + full['PrinterID'] + '" title="Edit"><i class="fa fa-pencil"></i></a>';
                            }
                        },
                        {
                            "data": "action",
                            "autowidth": true,
                            "mRender": function (data, type, full) {
                                return '<a href="#" onclick="DeleteData(' + full['PrinterID'] + ')" title="Delete"><i class="fa fa-trash-o txt-color-red"></i></a>';
                            }
                        }
                    ],
                    "order": [0, 'asc'],
                    "oLanguage": {
                        "sSearch": '<span class="input-group-addon"><i class="glyphicon glyphicon-search"></i></span>'
                    }
                });
        });
    </script>
}