SourceCode/Web/RINOR_POS/ViewModels/shopViewModel.cs
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using RINOR_POS;

namespace RINOR_POS.Models
{
    public class shopViewModel
    {
        public shopViewModel()
        {
            brand_list = new List<pos_brand_data>();
            merchant_list = new List<pos_merchant_data>();
            shop_list = new List<pos_shop_data>();
            Province_list = new List<pos_province>();
            city_list = new List<pos_city>();
            region_list = new List<pos_region>();
        }

        [Key]
        public int ShopID { get; set; }

        [Display(Name = "Merchant Name")]
        public int MerchantID { get; set; }
        public virtual pos_merchant_data pos_merchant_data { get; set; }
        public List<pos_merchant_data> merchant_list { get; set; }

        [Display(Name = "Brand Name")]
        public int BrandID { get; set; }
        public virtual pos_brand_data pos_brand_data { get; set; }
        public List<pos_brand_data> brand_list { get; set; }

        public List<pos_province> Province_list { get; set; }
        public List<pos_city> city_list { get; set; }
        public List<pos_region> region_list { get; set; }

        [StringLength(10)]
        [Required]
        [Display(Name = "Shop Code")]
        public string ShopCode { get; set; }
        public virtual pos_shop_data pos_shop_data { get; set; }
        public List<pos_shop_data> shop_list { get; set; }

        [StringLength(150)]
        [Display(Name = "Shop Key")]
        public string ShopKey { get; set; }

        [StringLength(150)]
        [Required]
        [Display(Name = "Shop Name")]
        public string ShopName { get; set; }

        [Display(Name = "Is Shop")]
        public bool? IsShop { get; set; }

        [Display(Name = "Is Inventory")]
        public bool? IsInv { get; set; }

        [Display(Name = "Has Service Charge")]
        public bool? HasSC { get; set; }

        public int? IsSCBeforeDisc { get; set; }

        public decimal? SCPercent { get; set; }

        [StringLength(10)]
        public string VATCode { get; set; }

        public int? VATType { get; set; }

        [Display(Name = "Master Shop")]
        public bool? MasterShop { get; set; }

        [Display(Name = "Master Shop Link")]
        public int? MasterShopLink { get; set; }

        public int? ShowInReport { get; set; }

        public int? ShopTypeID { get; set; }

        public int? ShopCatID1 { get; set; }

        public int? ShopCatID2 { get; set; }

        public int? ShopCatID3 { get; set; }

        public int? ShopCatID4 { get; set; }

        public int? ShopCatID5 { get; set; }

        public int? ShopCatID6 { get; set; }

        public int? ShopCatID7 { get; set; }

        public int? ShopCatID8 { get; set; }

        public int? ShopCatID9 { get; set; }

        public int? ShopCatID10 { get; set; }

        [Display(Name = "Open Hour")]
        public TimeSpan? OpenHour { get; set; }

        [Display(Name = "Close Hour")]
        public TimeSpan? CloseHour { get; set; }

        [StringLength(100)]
        [Display(Name = "Company Name")]
        public string CompanyName { get; set; }

        [StringLength(255)]
        [Display(Name = "Company Address 1")]
        public string CompanyAddress1 { get; set; }

        [StringLength(255)]
        [Display(Name = "Company Address 2")]
        public string CompanyAddress2 { get; set; }

        [Display(Name = "Company Province")]
        public int? CompanyProvince { get; set; }

        [Display(Name = "Company City")]
        public int? CompanyCity { get; set; }

        [Display(Name = "Company Region")]
        public int? CompanyRegion { get; set; }

        public int? DisplayCompanyProvinceLangID { get; set; }

        [StringLength(50)]
        [Display(Name = "Company Zip Code")]
        public string CompanyZipCode { get; set; }

        [StringLength(50)]
        [Display(Name = "Company Telephone")]
        public string CompanyTelephone { get; set; }

        [StringLength(50)]
        [Display(Name = "Company Fax")]
        public string CompanyFax { get; set; }

        [StringLength(3)]
        [Display(Name = "Company Country")]
        public string CompanyCountry { get; set; }

        [StringLength(50)]
        [Display(Name = "Company Tax ID")]
        public string CompanyTaxID { get; set; }

        [StringLength(50)]
        [Display(Name = "Company Register ID")]
        public string CompanyRegisterID { get; set; }

        [StringLength(255)]
        [Display(Name = "Branch")]
        public string BranchName { get; set; }

        [StringLength(50)]
        [Display(Name = "Branch No")]
        public string BranchNo { get; set; }

        [Display(Name = "Company Register Location")]
        public int? CompanyRegisterLocation { get; set; }

        [StringLength(255)]
        [Display(Name = "Branch Name In Full Tax Report")]
        public string BranchNameInFullTaxReport { get; set; }

        [StringLength(255)]
        public string AccountingCode { get; set; }

        [StringLength(50)]
        public string TaxPOSID { get; set; }

        [StringLength(100)]
        [Display(Name = "Delivery Name")]
        public string DeliveryName { get; set; }

        [StringLength(255)]
        [Display(Name = "Delivery Address 1")]
        public string DeliveryAddress1 { get; set; }

        [StringLength(255)]
        [Display(Name = "Delivery Address 2")]
        public string DeliveryAddress2 { get; set; }

        [Display(Name = "Delivery Province")]
        public int? DeliveryProvince { get; set; }

        [Display(Name = "Delivery City")]
        public int? DeliveryCity { get; set; }

        [Display(Name = "Delivery Region")]
        public int? DeliveryRegion { get; set; }

        [StringLength(50)]
        [Display(Name = "Delivery Zip Code")]
        public string DeliveryZipCode { get; set; }

        [StringLength(50)]
        [Display(Name = "Delivery Telephone")]
        public string DeliveryTelephone { get; set; }

        [StringLength(50)]
        [Display(Name = "Delivery Fax")]
        public string DeliveryFax { get; set; }

        [StringLength(50)]
        [Display(Name = "IP Address")]
        public string IPAddress { get; set; }

        [StringLength(100)]
        public string Addtional { get; set; }

        public int? ProductLevelOrder { get; set; }

        [StringLength(50)]
        public string SLOC { get; set; }

        [StringLength(20)]
        public string PTTShopCode { get; set; }

        [Display(Name = "Start Sale Date")]
        public DateTime? StartSaleDate { get; set; }

        public int? StartMonth { get; set; }

        public int? StartYear { get; set; }

        public int? Deleted { get; set; }
    }
}

SourceCode/Web/RINOR_POS/Controllers/shopController.cs
using System;
using System.IO;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RINOR_POS.Models;
using System.Net.Http;
using Newtonsoft.Json;

namespace RINOR_POS.Controllers
{
    [Authorize]
    public class shopController : BaseController
    {
        private ModelPOSDB db = new ModelPOSDB();

        // GET: shop
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// list for index
        /// </summary>
        /// <returns>JSON</returns>
        public JsonResult GetIndexList()
        {
            db.Configuration.ProxyCreationEnabled = false;

            var _qry = (from a in db.pos_shop_data.Where(a => a.DeletedDate == null)

                        select new shopViewModel
                        {
                            ShopID = a.ShopID,
                            ShopCode = a.ShopCode,
                            ShopName = a.ShopName,
                            ShopKey = a.ShopKey,
                            IsShop = a.IsShop
                            //crud_sample = a
                        }).ToList<shopViewModel>();

            return Json(new { data = _qry }, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetCityList(int ProvinceID = 0)
        {
            var _CityList = (from cty in db.pos_city
                             where cty.DeletedDate == null && cty.ProvinceID == ProvinceID
                             select cty).ToList();

            return Json(_CityList, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetRegionList(int CityID = 0)
        {
            var _RegionList = (from rgn in db.pos_region
                               where rgn.DeletedDate == null && rgn.CityID == CityID
                               select rgn).ToList();

            return Json(_RegionList, JsonRequestBehavior.AllowGet);
        }
        // GET: crud/Create
        public ActionResult Create(int? id)
        {
            shopViewModel shopdata = new shopViewModel()
            {
                merchant_list = db.pos_merchant_data.Where(o => o.DeletedDate == null).ToList(),
                brand_list = new List<pos_brand_data>(),
                shop_list = new List<pos_shop_data>(),
                Province_list = db.pos_province.Where(o => o.DeletedDate == null).ToList()
            };

            return View(shopdata);
        }

        // POST: shop/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(shopViewModel shopdata)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    //User Transaction
                    pos_shop_data shop = new pos_shop_data();
                    shop.MerchantID = shopdata.MerchantID;
                    shop.BrandID = shopdata.BrandID;
                    //string Key = App_Helpers.SerialKey.GetHash(shopdata.ShopCode + DateTime.Today.ToString("ddMMyyyy"));
                    shop.ShopKey = "NA";
                    shop.ShopName = shopdata.ShopName;
                    shop.ShopCode = shopdata.ShopCode;
                    shop.CompanyName = shopdata.CompanyName;
                    shop.ShopName = shopdata.ShopName;
                    shop.BranchName = shopdata.BranchName;
                    if (shopdata.MasterShop == null)
                        shop.MasterShop = false;
                    else
                        shop.MasterShop = shopdata.MasterShop;
                    shop.MasterShopLink = shopdata.MasterShopLink;
                    if (shopdata.CompanyRegisterLocation != null)
                        shop.CompanyRegisterLocation = shopdata.CompanyRegisterLocation;
                    if (shopdata.IsShop == null)
                        shop.IsShop = false;
                    else
                        shop.IsShop = shopdata.IsShop;
                    if (shopdata.IsInv == null)
                        shop.IsInv = false;
                    else
                        shop.IsInv = shopdata.IsInv;
                    shop.BranchNameInFullTaxReport = shopdata.BranchNameInFullTaxReport;
                    shop.CompanyAddress1 = shopdata.CompanyAddress1;
                    shop.CompanyAddress2 = shopdata.CompanyAddress2;
                    shop.CompanyProvince = shopdata.CompanyProvince;
                    shop.CompanyCity = shopdata.CompanyCity;
                    shop.CompanyRegion = shopdata.CompanyRegion;
                    shop.CompanyZipCode = shopdata.CompanyZipCode;
                    shop.CompanyTelephone = shopdata.CompanyTelephone;
                    shop.CompanyFax = shopdata.CompanyFax;
                    if (shopdata.HasSC == null)
                        shop.HasSC = false;
                    else
                        shop.HasSC = shopdata.HasSC;
                    shop.DeliveryName = shopdata.DeliveryName;
                    shop.DeliveryAddress1 = shopdata.DeliveryAddress1;
                    shop.DeliveryAddress2 = shopdata.DeliveryAddress2;
                    shop.DeliveryProvince = shopdata.DeliveryProvince;
                    shop.DeliveryCity = shopdata.DeliveryCity;
                    shop.DeliveryRegion = shopdata.DeliveryRegion;
                    shop.DeliveryZipCode = shopdata.DeliveryZipCode;
                    shop.DeliveryTelephone = shopdata.DeliveryTelephone;
                    shop.DeliveryFax = shopdata.DeliveryFax;
                    shop.CompanyRegisterID = shopdata.CompanyRegisterID;
                    shop.IPAddress = shopdata.IPAddress;
                    if (shopdata.StartSaleDate != null)
                    {
                        shop.StartSaleDate = shopdata.StartSaleDate;
                        shop.OpenHour = shopdata.OpenHour;
                        shop.CloseHour = shopdata.CloseHour;
                    }
                    shop.SLOC = shopdata.SLOC;
                    shop.CreatedBy = UserProfile.employee_id;
                    shop.CreatedDate = DateTime.Now;
                    shop = db.pos_shop_data.Add(shop);
                    db.SaveChanges();

                    //Request Register to License
                    using (var client = new HttpClient())
                    {
                        
                        client.BaseAddress = new Uri(UserProfile.APIURLBase + "/api/APIRegisterShop?KeyToken=uptome");

                        //HTTP POST
                        var result = client.PostAsJsonAsync("", shop).Result;

                        if (result.IsSuccessStatusCode)
                        {
                            shop.ShopKey = "Waiting for registration key";
                            db.Entry(shop).State = EntityState.Modified;
                            db.SaveChanges();
                        }
                    }

                    List<pos_program_property> PreferencesList = (from pre in db.pos_program_property
                                                                  where (pre.Active == true)
                                                                  select pre).ToList<pos_program_property>();

                    foreach (pos_program_property Pre in PreferencesList)
                    {
                        pos_shop_property shopProperty = new pos_shop_property()
                        {
                            ShopID = shop.ShopID,
                            PropertyID = Pre.PropertyID,
                            PropertyName = Pre.PropertyName,
                            PropertyParam = Pre.PropertyParam,
                            PropertyDesp = Pre.PropertyDesp,
                            DefaultDecimalValue = Pre.DefaultDecimalValue,
                            DefaultTextValue = Pre.DefaultTextValue,
                            Active = Pre.Active,
                            Ordering = Pre.Ordering
                        };
                        shopProperty = db.pos_shop_property.Add(shopProperty);
                        db.SaveChanges();
                    }
                    return RedirectToAction("Index");
                }

            }
            catch (Exception ex)
            {
                string msgErr = string.Format("An unknown error has occurred , Please contact your system administrator. {0}", ex.Message);
                if (ex.InnerException != null)
                    msgErr += string.Format(" Inner Exception: {0}", ex.InnerException.Message);
                ModelState.AddModelError("", msgErr);
            }

            shopdata.merchant_list = db.pos_merchant_data.Where(o => o.DeletedDate == null).ToList();
            shopdata.brand_list = db.pos_brand_data.Where(o => o.DeletedDate == null).ToList();
            shopdata.shop_list = db.pos_shop_data.Where(o => o.DeletedDate == null && o.MasterShop == true).ToList();
            shopdata.Province_list = db.pos_province.Where(o => o.DeletedDate == null).ToList();

            return View(shopdata);
        }

        // GET: shop/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            pos_shop_data shopdata = db.pos_shop_data.Find(id);
            if (shopdata == null)
            {
                return HttpNotFound("Crud not found.");
            }

            shopViewModel shop = new shopViewModel();
            shop.merchant_list = db.pos_merchant_data.Where(o => o.DeletedDate == null).ToList();
            shop.brand_list = db.pos_brand_data.Where(o => o.DeletedDate == null).ToList();

SourceCode/Web/RINOR_POS/Views/shop/Index.cshtml
@model IEnumerable<RINOR_POS.Models.shopViewModel>

@{
    ViewBag.Title = "Manage Shop Data";
}

<div id="content">
    <!-- row -->
    <div class="row">
        <div class="col-xs-12 col-sm-9 col-md-9 col-lg-9">
            <h1 class="page-title txt-color-blueDark">

                <!-- PAGE HEADER -->
                <i class="fa-fw fa fa-pencil-square-o"></i>
                Manage Shop
                <span>
                    >
                    List Data
                </span>
            </h1>
        </div>

        <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">
            @if (ViewBag.CanCreate)
            {
                <!-- Button trigger modal -->
                <a class="btn btn-primary btn-lg pull-right header-btn hidden-mobile" href="@Url.Action("Create", "shop", new { id = 0 }, Request.Url.Scheme)"><i class='fa fa-plus'></i> Shop</a>
            }
            <input type="hidden" id="CanUpdate" value=@(ViewBag.CanUpdate.ToString().ToLower())>
            <input type="hidden" id="CanDelete" value=@(ViewBag.CanDelete.ToString().ToLower())>
        </div>
    </div>
    <section id="widget-grid" class="">
        <div class="row">
            <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="jarviswidget jarviswidget-color-darken" id="wid-id-0" data-widget-editbutton="false">

                    <header>
                        <span class="widget-icon"> <i class="fa fa-table"></i> </span>
                        <h2>Manage Shop Data List</h2>

                    </header>
                    <div>
                        <!-- widget edit box -->
                        <div class="jarviswidget-editbox">
                            <!-- This area used as dropdown edit box -->

                        </div>
                        <!-- end widget edit box -->
                        <div class="widget-body no-padding">
                            <table class="table table-striped table-bordered table-hover" width="100%" id="table_basic">
                                <thead>
                                    <tr>
                                        <th>
                                            @Html.DisplayNameFor(model => model.ShopCode)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.ShopName)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.ShopKey)
                                        </th>
                                        <th width="8%">Option</th>
                                        <th width="10%">Register</th>
                                        <th width="10%">Get License</th>
                                        <th width="10px">Edit</th>
                                        <th width="10px">Delete</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </article>
        </div>
    </section>
    <!-- Modal -->
    <div class="modal fade" id="InfoAsset" tabindex="-1" role="dialog"></div>
</div>

@section pagespecific {
    <script type="text/javascript">

        function DeleteData(id) {
            swal({
                title: "Are you sure want to Delete this data?",
                text: "(this process can\'t be undo)",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Yes, Sure!",
                closeOnConfirm: false,
                closeOnEsc: false,
                closeOnCancel: false,
                showLoaderOnConfirm: true,
                preConfirm: () => {
                    return new Promise(() => {
                        //ajax side
                        swal({
                            title: 'Please wait... delete data in progress....',
                            onOpen: function () {
                                swal.showLoading()
                                $.ajax({
                                    type: "GET",
                                    url: baseURL + "shop/DeleteItem/" + id,
                                    success: function (data) {
                                        if (data == "1") {
                                            swal.close();
                                            swal("Success", "Success Delete Data", "success");
                                            setTimeout(location.reload(true), 5000);
                                            //window.location.href = "/asset_registration/index";
                                        }
                                        else {
                                            swal("Failed", "Failed Delete Data", "error");
                                        }

                                    },
                                });
                            }
                        });
                    })
                },
                allowOutsideClick: () => !swal.isLoading()
            }).then((result) => {
                if (result.dismiss) {
                    swal("Cancel", "You Cancel Delete Data", "error");
                }
            });
        }
        function ResendLicense(id) {
            swal({
                title: "Are you sure want to Register this data?",
                text: "(this process can\'t be undo)",
                //type: "warning",
                showCancelButton: true,
                //confirmButtonColor: "#DD6B55",
                confirmButtonText: "Yes, Sure!",
                closeOnConfirm: false,
                closeOnEsc: false,
                closeOnCancel: false,
                showLoaderOnConfirm: true,
                preConfirm: () => {
                    return new Promise(() => {
                        //ajax side
                        swal({
                            title: 'Please wait... register data in progress....',
                            onOpen: function () {
                                swal.showLoading()
                                $.ajax({
                                    type: "GET",
                                    url: baseURL + "shop/ResendShop/" + id,
                                    success: function (data) {
                                        if (data == "1") {
                                            swal.close();
                                            swal("Success", "Success Register Data", "success");
                                            setTimeout(location.reload(true), 5000);
                                            //window.location.href = "/asset_registration/index";
                                        }
                                        else if (data == "2") {
                                            swal("Failed", "Data is already Registered", "error");
                                        }
                                        else {
                                            swal("Failed", "Failed Register Data", "error");
                                        }

                                    },
                                });
                            }
                        });
                    })
                },
                allowOutsideClick: () => !swal.isLoading()
            }).then((result) => {
                if (result.dismiss) {
                    swal("Cancel", "You Cancel Register Data", "error");
                }
            });
        }

        function GetLicense(id) {
            swal({
                title: "Are you sure want to get License Key?",
                text: "(this process can\'t be undo)",
                //type: "warning",
                showCancelButton: true,
                //confirmButtonColor: "#DD6B55",
                confirmButtonText: "Yes, Sure!",
                closeOnConfirm: false,
                closeOnEsc: false,
                closeOnCancel: false,
                showLoaderOnConfirm: true,
                preConfirm: () => {
                    return new Promise(() => {
                        //ajax side
                        swal({
                            title: 'Please wait... get license in progress....',
                            onOpen: function () {
                                swal.showLoading()
                                $.ajax({
                                    type: "GET",
                                    url: baseURL + "shop/GetShopKey/" + id,
                                    success: function (data) {
                                        if (data == "1") {
                                            swal.close();
                                            swal("Success", "Success Get License Data", "success");
                                            setTimeout(location.reload(true), 5000);
                                            //window.location.href = "/asset_registration/index";
                                        }
                                        else {
                                            swal("Failed", "Failed Get License Data", "error");
                                        }

                                    },
                                });
                            }
                        });
                    })
                },
                allowOutsideClick: () => !swal.isLoading()
            }).then((result) => {
                if (result.dismiss) {
                    swal("Cancel", "You Cancel Register Data", "error");
                }
            });
        }
        $(document).ready(function () {
            let canupdate = $("#CanUpdate").val();
            let candelete = $("#CanDelete").val();
            $('#table_basic').dataTable(
                {
                    "ajax": {
                        "url": baseURL + "shop/GetIndexList/",
                        "type": "GET",
                        "datatype": "json",
                    },
                    "dom": "<'dt-toolbar'<'col-xs-12 col-sm-6'f><'col-sm-6 col-xs-12 hidden-xs'l>r>" + "t"
                        + "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-xs-12 col-sm-6'p>>",
                    "columns": [
                        { "data": "ShopCode", "autoWidth": true },
                        { "data": "ShopName", "autoWidth": true },
                        { "data": "ShopKey", "autoWidth": true },
                        {
                            "data": "option",
                            "autowidth": true,
                            "mRender": function (data, type, full) {
                                return '<a href="' + baseURL + 'shop/Option/' + full['ShopID'] + '"><i class="fa fa-process"></i></a>';
                            }
                        },
                        {
                            "data": "action",
                            "autowidth": true,
                            "mRender": function (data, type, full) {
                                return '<a href="#" onclick="ResendLicense(' + full['ShopID'] + ')" title="Register"><i class="fa fa-send"></i></a>';
                            }
                        },
                        {
                            "data": "action",
                            "autowidth": true,
                            "mRender": function (data, type, full) {
                                return '<a href="#" onclick="GetLicense(' + full['ShopID'] + ')" title="Get License"><i class="fa fa-cloud-download"></i></a>';
                            }
                        },
                        {
                            "data": "action",
                            "autowidth": true,
                            "mRender": function (data, type, full) {
                                if (canupdate == 'true')
                                    return '<a href="' + baseURL + 'shop/edit/' + full['ShopID'] + '"><i class="fa fa-pencil"></i></a>';
                                else
                                    return '<i class="fa fa-ban txt-color-red" title="Access Denied"></i>'
                            }
                        },
                        {
                            "data": "action",
                            "autowidth": true,
                            "mRender": function (data, type, full) {
                                if (candelete == 'true')
                                    return '<a href="#" onclick="DeleteData(' + full['ShopID'] + ')"><i class="fa fa-trash-o txt-color-red"></i></a>';
                                else
                                    return '<i class="fa fa-ban txt-color-red" title="Access Denied"></i>'
                            }
                        }
                    ],
                    "order": [1, 'asc'],
                    "oLanguage": {
                        "sSearch": '<span class="input-group-addon"><i class="glyphicon glyphicon-search"></i></span>'
                    }
                });
        });
    </script>
}